name: axe
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.6
      - name: Save changed files
        run: |
          echo "CHANGED_FILES=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: yarn
      - run: yarn dist
      - name: Run docs site	
        run: |	
          npm run dev & npx wait-on http://localhost:8000
      - name: Run axe script
        run: |
          script/axe-docs
